version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: unless-stopped
    networks:
      - drupal
    ports:
      - '$NGINX_PORT:80'
    volumes:
      - drupal:/opt/drupal/web

  drupal:
    hostname: $HOSTNAME
    build:
      context: .
      dockerfile: Dockerfile.drupal
    env_file:
      - .env
    networks:
      - drupal
    restart: unless-stopped
    volumes:
      - drupal:/opt/drupal/web
      - $HOME/.ssh:/root/.ssh:ro

  mysql:
    image: mysql/mysql-server:5.7.34-1.2.3-server
    env_file:
      - .env
    networks:
      - drupal
    ports:
      - '$MYSQL_PORT:3306'
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql

networks:
  drupal:

volumes:
  db:
  drupal:
