FROM drupal:9.5.5-php8.1-fpm-buster

RUN apt update && apt install -y git unzip vim libicu-dev && docker-php-ext-install intl

COPY ./entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

CMD ["php-fpm"]